#
# server {
# 	redirect 300 but;
# 	listen 0.0.0.0:2000;
# 	location /a/ {
# 		allowed_methods GET;
# 		redirect 301 /x/;
# 	}
# 	server_name server1;
# }
#

server {
	listen 0.0.0.0:2000;
	redirect 300 lll;
	location /b/a/c/d/e {
		allowed_methods GET;
		redirect 303 /match;
	}
	server_name server1;
}

# server {
# 	redirect 300 o;
# location /hey/ {
# 		allowed_methods GET;
# 		redirect 302 /usr/bin/;
# 	}
# 	listen 0.0.0.0:2000;
# 	server_name server2;
# }
#
# server {
# 	redirect 300 x;
# location /heys/ {
# 		allowed_methods GET;
# 		autoindex on;
# 		index match;
# 		redirect 302 /usr/bin/3;
# 	}
# 	listen 0.0.0.0:2000;
# 	server_name server3;
# }
#
#

