
server {
	redirect 303 hey;
	listen 8000;
# isssue if i remvoe that line
	allowed_methods GET;
	location /facebook/ {
		allowed_methods GET;
		redirect 300 facebook.com;
	}

	location /google/ {
		allowed_methods GET;
		redirect 300 google.com;
	}
	server_name server2;

}


server {
	redirect 303 3;
	listen 8000;
	allowed_methods GET;
	location /home/hsacr/COMMON_CORE/webserver/work/WebServer/ {
		allowed_methods GET;
		index Makefile;
		# autoindex on;
		# redirect 300 twetter.com;
	}
	server_name server3;
}
