#
# server {
# 	redirect 300 but;
# 	listen 0.0.0.0:2000;
# 	location /a/ {
# 		allowed_methods GET;
# 		redirect 301 /x/;
# 	}
# 	server_name server1;
# }
#
server {
	location /b/ {
		allowed_methods POST;
		redirect 303 /match;
	}
}
server {
	redirect 300 o;
location /hey/ {
		allowed_methods GET;
		redirect 302 /usr/bin/;
	}
	listen 0.0.0.0:2000;
	server_name server2;
}

server {
	redirect 300 3;
location /heys/ {
		allowed_methods GET;
		autoindex on;
		index match;
		redirect 302 /usr/bin/3;
	}
	listen 0.0.0.0:2000;
	server_name server3;
}

