server {
	listen localhost:9090;
	server_name server1;
	location /test/autoindex1/ {
		autoindex on;
		allowed_methods GET POST DELETE;
	}
	location /test/a/b/autoindex {
		autoindex on;
		allowed_methods GET;
	}

}


server {
	listen localhost:9090;
	location /test/autoindex2/ {
		autoindex on;
		allowed_methods GET POST DELETE;
	}
	server_name server2;
}

