server {
	listen 6100;
	location / {
		alias //home/hsacr/COMMON_CORE/webserver/tests/cgi/apache-cgi/cgi-bin;
		access_log /home/hsacr/COMMON_CORE/webserver/work/WebServer/access.log;
		client_max_body_size 2M;
		cgi .sh .out .hey .cgi .py;
		allowed_methods GET POST DELETE;
	}
}
