server {
	listen 5551;
	allowed_methods GET POST DELETE;
	autoindex on;
	location / {
		alias /home/hsacr/COMMON_CORE/webserver/work/WebServer/www/cgi-bin;
		access_log /home/hsacr/COMMON_CORE/webserver/work/WebServer/access.log;
		client_max_body_size 2M;
		cgi .sh .out .hey .cgi .py;
	}
	location /data/ {
		alias /tmp/VIDEOS/;
	}
}
