server {
	listen 5551;
	allowed_methods GET POST DELETE;
	autoindex on;
	error_page 500  /home/zfarouk/Desktop/projects/web/error_pages/400.html;
	location / {
		alias /home/zfarouk/Desktop/projects/web/www/cgi-bin;
		client_max_body_size 2M;
		cgi .sh .out .hey .cgi .py;
	}
	location /data/ {
		alias /tmp/VIDEOS/;
	}
}
