server {
    listen 127.0.0.1:8080;
    server_name 'localhost';
    
    # ==========================================
    # SERVER DEFAULTS (The Inheritance Baseline)
    # ==========================================
    root /var/www/default_root;
    index server_index.html;
    upload_dir /var/www/uploads;
    autoindex off;

    # ==========================================
    # TEST CASE 1: Exact Match Override (=)
    # ==========================================
    # Action: Should instantly return this block, ignoring prefix logic.
    location /login {
        root /home/laghrabichaimaa/WebServ;
        allowed_methods GET POST;
        index login.html;
    }

    # ==========================================
    # TEST CASE 2: The Fast Path (hasNoConfig)
    # ==========================================
    # Action: This is completely empty. Your `hasNoConfig()` should catch it
    # and overwrite this leaf node with the Server defaults perfectly.
    location /assets/images {

    }

    location /assets {
        root /chaimaa;
    }

    # ==========================================
    # TEST CASE 3: The Granular Path (Partial Config)
    # ==========================================
    # Action: Has some directives but missing others. It should inherit 
    # the server's `root` and `upload_dir`, but keep its own `autoindex`.
    location /downloads/ {
        autoindex on;
    }

    # ==========================================
    # TEST CASE 4: Implicit Intermediate Nodes
    # ==========================================
    # Action: The tree builder has to create `/api` and `/api/v1` automatically
    # before it can create `/api/v1/users`. Those intermediate nodes must 
    # inherit the server defaults via your intermediate fallback logic.
    location /api/v1/users {
        root /var/www/database;
        allowed_methods GET POST;
    }

    # ==========================================
    # TEST CASE 5: Redirects & Trailing Slashes
    # ==========================================
    location /legacy/ {
        redirect 301 /new_page;
    }
}

server {
    listen 127.0.0.1:8000;
    server_name 'myapp.local' 'app1';
    allowed_methods GET POST;
    
    root /home/laghrabichaimaa/WebServ;
    index app.html;

    location / {
        allowed_methods GET POST;
        index welcome.html;
    }

    # Empty block to test your hasNoConfig() fast-path
    location /data {
        allowed_methods GET;
        index www.html;
    }
}

# ==========================================
# SERVER 3: Port-Based Virtual Host (Port 9090)
# ==========================================
# This listens on a completely different port.
server {
    listen 127.0.0.1:9090;
    server_name 'localhost' 'myapp.local';
    
    root /var/www/server3_admin;
    index admin.html;

    location /api/ {
        allowed_methods GET POST;
    }
}