server {
	listen localhost:80;
	listen localhost:1000;
	listen localhost:200;
	listen localhost:400;

	server_name 'a' 'b' 'c' 'conflict';
	location / {

	}
location /data/www {

	}
}

server {
	listen localhost:80;
	listen localhost:1000;
	listen localhost:200;
	listen localhost:400;
	server_name 'e' 'g' 'z' 'conflict';
}
