server {
	listen localhost:8000;
	location /home/zfarouk// {
		root /;
		allowed_methods GET DELETE;
		autoindex on;

	}
	location /upload{  #/upload/dir/dir/dir/hey
		root /home/zfarouk/Desktop;
		allowed_methods GET POST;
	}
	allowed_methods GET;
}