server {
	listen 8000;
	error_page 404 /home/zfarouk/Desktop/projects/web/error_pages/404.html;
	error_page 400 /home/zfarouk/Desktop/projects/web/error_pages/400.html;
	error_page 403 /home/zfarouk/Desktop/projects/web/error_pages/403.html;
	root /;
	autoindex on;
	allowed_methods GET;
}
