# autoindex server_name listen root index
server  {
	location / {
		upload_dir 'file.html';
	}
	location /bin {
		upload_dir 'but.html';
	}
	server_name 'hamza';
	listen 0.0.0.0:800;

	server_name 'hamza';
	listen 0.0.0.0:80;


}

types {
	maybe html;
# }
