server {
	listen 2.2.2.2:80;
	server_name '4';
}
server {
	listen 2.2.2.2:80;
	server_name '2';
}
server {
	listen 2.2.2.2:80;
	server_name '3';
}

server {
	listen 1.1.1.1:80;
	server_name '10';
}
server {
	listen 1.1.1.1:80;
	server_name '11';
}
server {
	listen 1.1.1.1:80;
	server_name '12';
}
