server {
	listen localhost:8000;
	location / {
		root /home/hsacr/COMMON_CORE/webserver/work/WebServer/intra_test/;
		allowed_methods GET;
		autoindex on;
	}
	# TODO: do something
	location / {

	}
}
