server {
	autoindex on;
	listen 8000;

	location /etc/ {
		index not_found;
		autoindex off;
		allowed_methods GET POST DELETE;
	}

	location /bin/ {
		index ls;
		allowed_methods GET POST DELETE;
	}
}
