server {
	listen 8000;
	location /usr/bin/ {
		index yes;
		allowed_methods GET POST DELETE;
	}
	location /bin/ {
		allowed_methods GET POST DELETE;
	}
}

server {
	listen 8000;
	location /etc/ {
		index yes;
		allowed_methods GET POST DELETE;
	}
	location /var/ {
		allowed_methods GET POST DELETE;
	}
	server_name server2 1337;
}
