server {
	listen localhost:8000;
	location /bin/ {
		root /usr/;
		autoindex off;
		allowed_methods GET;
	}
location /uploads/ {
    allowed_methods GET POST;
    root /;
    alias /images/;
    upload_dir /var/www/uploads;
}

location /images/uploads/ {
    allowed_methods GET POST;
    root /;
    alias /gallery/;
    # upload_dir /var/www/gallery;
} 
}


