server {
	server_name 'ls' 'but';
	access_log '/var/log/server/';
	allowed_methods GET POST;
	root /home/laghrabichaimaa/WebServ;;
	index 'file.html' file.html;
	upload_dir '/var/store/data/';
	listen 0.0.0.0:8000;
	autoindex on;
	location / {
		index lol.html;
	}
	location /data {
		allowed_methods GET POST;
		index lol.html;
	}
	location /admin {

	}
}
