server {
    listen localhost:8000;
    location / {
        allowed_methods GET;
				autoindex on;
        # cgi .sh;
    }
}

# server {
#     listen localhost:8000;
#     location / {
#          root /home/laghrabichaimaa/WebServ;
#         allowed_methods GET;
#         index passwd;
#         autoindex on;
#         cgi .sh;
#         # index passwd;
#     }
#     server_name hey;
# }
