server {
	listen 1.1.1.1:80;
	upload_dir '/data/hey';
	autoindex on;
	autoindex off;
}

server {
	listen 1.1.1.1:80;
	index hey.html but.lkasjdf;
	server_name 'but' 'whoami' 'localhost';
}

server {
	listen 1.1.1.1:80;
	server_name 'hey';
}
