server {
	listen 1.1.1.1:109;
	upload_dir '/data/hey';
	autoindex on;
	autoindex off;
	allowed_methods GET POST DELETE;
}

server {
	listen 2.2.2.2:200;
	index hey.html but.lkasjdf;
	server_name 'but' 'whoami' 'localhost';
	# max_client_body_size 20;
	location / {
		root /data/www;
		index file.html;
	}
}

server {
	listen google.com:306;
	server_name 'a' 'b';
	index index.html index.php;
}
server {
	listen localhost:306;
	index index.html index.php;
	server_name 'a' 'b';
}
server {
	listen localhost:306;
	listen 4.4.4.4:306;
	server_name 'hey';
}
server {
	listen 6.6.6.6:306;
	server_name 'a' 'b';
	location / {
		index file.xml;
	}
}


server {
	listen 1.1.1.1:105;
	listen 1.1.1.1:305;
	upload_dir '/data/hey';
	autoindex on;
	autoindex off;
}

server {
	listen 1.1.1.1:200;
	index hey.html but.lkasjdf;
	server_name 'but' 'whoami' 'localhost';
	# max_body_size 1000;
}

server {
	listen 1.1.1.1:300;
	server_name 'hey';
}
