# Server 1: Default on 8080
server {
    listen 8080;
    server_name 'localhost' 'media.local';
    
    location / {
        allowed_methods GET;
        root /home/claghrab/Desktop/mini-web/gemini-test/server1;
        autoindex on;
    }
}

# Server 2: Virtual Host on 8080 (Shares port with Server 1)
server {
    listen 8080;
    server_name api.local;
    
    location / {
        allowed_methods GET POST;
        alias /home/claghrab/Desktop/mini-web/gemini-test/server2;
        index output.html;
        autoindex off;
    }
}

# Server 3: Dedicated Port 8081
server {
    listen 8081;
    server_name media.local;
    
    location / {
        allowed_methods GET;
        root /home/claghrab/Desktop/mini-web/gemini-test/server3;
        autoindex on;
    }
}