# =========================================
# SERVER 1: The Main Web App (Port 8080)
# =========================================
server {
    listen 8080;
    server_name localhost;
    client_max_body_size 10M;
    error_page 404 /errors/404.html;

    location / {
        allowed_methods GET;
        root /home/claghrab/Desktop/mini-web/gemini-test/main;
        index index.html;
    }

    location /uploads/ {
        allowed_methods GET POST DELETE;
        root /home/claghrab/Desktop/mini-web/gemini-test/main;
        upload_dir /home/claghrab/Desktop/mini-web/gemini-test/main/uploads;
    }

    location /cgi-bin/ {
        allowed_methods GET POST;
        root /home/claghrab/Desktop/mini-web/gemini-test/main;
    }
}

# =========================================
# SERVER 2: The API (Port 8080 - Virtual Host)
# =========================================
server {
    listen 8080;
    server_name api.local;
    client_max_body_size 1M;

    # 1. Broad match
    location /api/ {
        allowed_methods GET POST;
        root /home/claghrab/Desktop/mini-web/gemini-test/api;
        autoindex off;
    }

    # 2. Longest prefix trap (Overrides /api/ with stricter rules)
    location /api/readonly/ {
        allowed_methods GET;
        root /home/claghrab/Desktop/mini-web/gemini-test/api;
        autoindex on;
    }

    # 3. Alias test
    location /assets/ {
        allowed_methods GET;
        alias /home/claghrab/Desktop/mini-web/gemini-test/shared_assets/;
        autoindex on;
    }
}

# =========================================
# SERVER 3: The Legacy Server (Port 8081)
# =========================================
server {
    listen 8081;
    server_name legacy.local;

    location / {
        allowed_methods GET;
        root /home/claghrab/Desktop/mini-web/gemini-test/legacy;
        index default.html;
    }

    location /docs/ {
        allowed_methods GET;
        root /home/claghrab/Desktop/mini-web/gemini-test/legacy;
        autoindex on;
    }

    # HTTP Redirection Test
    location /old-docs/ {
        allowed_methods GET;
        return 301 /docs/;
    }
}