server {
    listen 8080;
    server_name localhost;
    client_max_body_size 5M;
    error_page 404 /404.html;

    # 1. Main Static Site
    location / {
        allowed_methods GET;
        root /home/claghrab/Desktop/mini-web/gemini-test/www;
        # index index.html;
        autoindex on;
    }

    # 2. Uploads Directory
    location /uploads/ {
        allowed_methods GET POST DELETE;
        root /home/claghrab/Desktop/mini-web/gemini-test;
        upload_dir /home/claghrab/Desktop/mini-web/gemini-test/uploads;
        autoindex on;
    }

    # 3. CGI Directory
    location /cgi-bin/ {
        allowed_methods GET POST;
        cgi .php;
        root /home/claghrab/Desktop/mini-web/gemini-test;
        index script.php;
    }
}