server {
    listen 8080;
    server_name localhost;
    client_max_body_size 11B;

    location / {
        allowed_methods GET POST DELETE;
        # root /home/claghrab/Desktop/mini-web/gemini-test/www;
        root /home/claghrab/Desktop/mini-web/gemini-test/main/uploads;
        index index.html;
        autoindex on;
    }
}